- name: deploy a master
  shell: |
    virt-install --name {{ ocp_cluster_name }}-master-{{ item.num }} \
    --disk size={{ master_disk_size }} --ram {{ rhcos_master_node_memory }} --cpu host --vcpus {{ rhcos_master_node_cpu }} \
    --os-type linux --os-variant rhel7 \
    --network network={{ ocp_vir_net }} --noreboot --noautoconsole \
    --pxe --mac={{ item.mac }}
  loop:
    - { num: 1, mac: "52:54:00:7d:2d:b2" }
    - { num: 2, mac: "52:54:00:7d:2d:b3" }
    - { num: 3, mac: "52:54:00:7d:2d:b4" }
