- name: generate a user name and a password 
  command: htpasswd -bBc /opt/registry/auth/htpasswd {{ podman_username }} {{ podman_password }}

- name: open the require ports for registry service
  firewalld:
    port: 5000/tcp
    zone: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - internal
    - public

- name: create the mirror registry container to utility server
  block:
   - template:
       src: podman.sh.j2
       dest: /tmp/podman.sh
       mode: 0744
   - command: /bin/sh /tmp/podman.sh
     ignore_errors: yes

- name: create the pull_secret as file
  copy:
    content: "{{ pull_sec }}"
    dest: /tmp/ocp4_pull_secret.json

- name: convert to the pull secret by jq
  shell: cat /tmp/ocp4_pull_secret.json | jq .  > /tmp/pull_secret.json

- name: copy oc command to image mirror server
  copy:
    src: oc
    dest: /tmp/oc
    mode: 744

- name: mirror the repository
  shell: "/tmp/oc adm -a /tmp/pull_secret.json release mirror --from=quay.io/openshift-release-dev/ocp-release:{{ ocp_version }}-{{ ocp_architecture }} --to={{ ocp_cluster_name }}.{{ ocp_base_domain }}:5000/ocp4/openshift4 --to-release-image={{ ocp_cluster_name }}.{{ ocp_base_domain }}:5000/ocp4/openshift4:{{ ocp_version }}-{{ ocp_architecture }}"

